{
  gSystem->Load("../../libPhysicsToolsKinFitter.so");
  gROOT->LoadMacro("../../HbbHbb_MeasureResolutionBias.cc++");
  HbbHbb_MeasureResolutionBias("Graviton260GeV_regressed");
  HbbHbb_MeasureResolutionBias("Graviton270GeV_regressed");
  HbbHbb_MeasureResolutionBias("Graviton300GeV_regressed");
  HbbHbb_MeasureResolutionBias("Graviton400GeV_regressed");
  HbbHbb_MeasureResolutionBias("Graviton600GeV_regressed");
  HbbHbb_MeasureResolutionBias("Graviton800GeV_regressed");
  HbbHbb_MeasureResolutionBias("Graviton1000GeV_regressed");
  HbbHbb_MeasureResolutionBias("Graviton1200GeV_regressed");
}
