/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                            *
 * This code was autogenerated by RooClassFactory                            *
 ******************************************************************************/

// Your description goes here... 

#include "Riostream.h" 

#include "Falling_1.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(Falling_1) 

 Falling_1::Falling_1(const char *name, const char *title, 
                 RooAbsReal& _x,
                 RooAbsReal& _p0,
                 RooAbsReal& _p1,
                 RooAbsReal& _p2) :

   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   p0("p0","p0",this,_p0),
   p1("p1","p1",this,_p1),
   p2("p2","p2",this,_p2)

 { 
 } 


 Falling_1::Falling_1(const Falling_1& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   p0("p0",this,other.p0),
   p1("p1",this,other.p1),
   p2("p2",this,other.p2)

 { 
 } 

Double_t Falling_1::evaluate() const
{
   Double_t result=p0 +p1*pow(x,p2);
   return result;
}




