/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                            *
  * This code was autogenerated by RooClassFactory                            * 
 ******************************************************************************/

#ifndef FALLING_h
#define FALLING_h

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Falling : public RooAbsPdf {
public:
  Falling() {} ; 
  Falling(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2);
  Falling(const Falling& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Falling(*this,newname); }
  inline virtual ~Falling() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(Falling,1) // Your description goes here...
};
 
#endif
