/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef GAUSSEXPXCHEBYCHEV3
#define GAUSSEXP

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class GaussExpXChebychev3 : public RooAbsPdf {
public:
  GaussExpXChebychev3() {} ; 
  GaussExpXChebychev3(const char *name, const char *title,
	                    RooAbsReal& _x,
	                    RooAbsReal& _p0,
	                    RooAbsReal& _p1,
	                    RooAbsReal& _p2,
                      RooAbsReal& _p3, // Cheb min
                      RooAbsReal& _p4, // Cheb max
                      RooAbsReal& _p5, // c0
                      RooAbsReal& _p6, // c1
                      RooAbsReal& _p7, // c2
                      RooAbsReal& _p8  // c3
                     );
  GaussExpXChebychev3(const GaussExpXChebychev3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new GaussExpXChebychev3(*this,newname); }
  // inline virtual ~GaussExpXChebychev3() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;
  RooRealProxy p4 ;
  RooRealProxy p5 ;
  RooRealProxy p6 ;
  RooRealProxy p7 ;
  RooRealProxy p8 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(GaussExpXChebychev3,1) // Your description goes here...
};
 
#endif
