/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef LOGISTICXCHEBYCHEV3
#define LOGISTICXCHEBYCHEV3

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class LogisticXChebychev3 : public RooAbsPdf {
public:
  LogisticXChebychev3() {} ; 
  LogisticXChebychev3(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2,
	      RooAbsReal& _p3,
	      RooAbsReal& _p4,
        RooAbsReal& _p5,
        RooAbsReal& _p6,
        RooAbsReal& _p7);
  LogisticXChebychev3(const LogisticXChebychev3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new LogisticXChebychev3(*this,newname); }
  inline virtual ~LogisticXChebychev3() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;
  RooRealProxy p4 ;
  RooRealProxy p5 ;
  RooRealProxy p6 ;
  RooRealProxy p7 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(LogisticXChebychev3,1) // Your description goes here...
};
 
#endif
