/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef LOWMASSBACKGROUNDPDF
#define LOWMASSBACKGROUNDPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class LowMassBackgroundPDF : public RooAbsPdf {
public:
  LowMassBackgroundPDF() {} ; 
  LowMassBackgroundPDF(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2,
        RooAbsReal& _p3,
        RooAbsReal& _p4);
  LowMassBackgroundPDF(const LowMassBackgroundPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new LowMassBackgroundPDF(*this,newname); }
  inline virtual ~LowMassBackgroundPDF() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;
  RooRealProxy p4 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(LowMassBackgroundPDF,1) // Your description goes here...
};
 
#endif
