/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                            *
  * This code was autogenerated by RooClassFactory                            * 
 ******************************************************************************/

#ifndef NOVOERF
#define NOVOERF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class NovoErf : public RooAbsPdf {
public:
  NovoErf() {} ; 
  NovoErf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1);
  NovoErf(const NovoErf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new NovoErf(*this,newname); }
  inline virtual ~NovoErf() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(NovoErf,1) // Your description goes here...
};
 
#endif
