/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef QCD_DIJET_X
#define QCD_DIJET_X

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class QCD_DiJet_x : public RooAbsPdf {
public:
  QCD_DiJet_x() {} ; 
  QCD_DiJet_x(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2,
        RooAbsReal& _p3);
  QCD_DiJet_x(const QCD_DiJet_x& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new QCD_DiJet_x(*this,newname); }
  inline virtual ~QCD_DiJet_x() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(QCD_DiJet_x,1) // Your description goes here...
};
 
#endif
