/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "QCD_DiJet.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(QCD_DiJet) 

 QCD_DiJet::QCD_DiJet(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _p0,
                        RooAbsReal& _p1,
                        RooAbsReal& _p2) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   p0("p0","p0",this,_p0),
   p1("p1","p1",this,_p1),
   p2("p2","p2",this,_p2)
 { 
 } 


 QCD_DiJet::QCD_DiJet(const QCD_DiJet& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   p0("p0",this,other.p0),
   p1("p1",this,other.p1),
   p2("p2",this,other.p2)
 { 
 } 



 Double_t QCD_DiJet::evaluate() const 
 { 
   Double_t x_f=x/8000.;
   Double_t f=pow(1.-x_f, p0)/pow(x_f, p1+p2*log(x_f));
   // std::cout<<"p0 = "<<p0<<" p1 = "<<p1<<", p2 = "<<p2<<", f = "<<f<<std::endl;
   return f; 
 } 



