/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef QCD_DIJET
#define QCD_DIJET

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class QCD_DiJet : public RooAbsPdf {
public:
  QCD_DiJet() {} ; 
  QCD_DiJet(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2);
  QCD_DiJet(const QCD_DiJet& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new QCD_DiJet(*this,newname); }
  inline virtual ~QCD_DiJet() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(QCD_DiJet,1) // Your description goes here...
};
 
#endif
