setenv dir /eos/uscms/store/user/souvik/HbbHbb_Run2/V12

root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion260GeV", "Radion260GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion270GeV", "Radion270GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion300GeV", "Radion300GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion350GeV", "Radion350GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion400GeV", "Radion400GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion450GeV", "Radion450GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion500GeV", "Radion500GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion550GeV", "Radion550GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion600GeV", "Radion600GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion650GeV", "Radion650GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion700GeV", "Radion700GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion800GeV", "Radion800GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("$dir/Radion900GeV", "Radion900GeV")'
