root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion260GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion270GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion300GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion350GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion400GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion450GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion500GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion550GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion600GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion650GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion700GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion800GeV")'
root -l -b -q 'HbbHbb_PreSelection.cc++("/Users/souvik/HbbHbb_Run2/13TeV/V12", "Radion900GeV")'

say "Pre selection of signal Monte Carlo done."
