root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion260GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion270GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion300GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion350GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion400GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion450GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion500GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion550GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion600GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion650GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion700GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion800GeV")'
root -l -b -q '../HbbHbb_MMRSelection.cc++("Signal", "Radion900GeV")'
say "MMR selection of signal Monte Carlo done."
