setenv dir /eos/uscms/store/user/lpchbb/HeppyNtuples/V23

root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph","JEC","JER","Trig","bTag",true)'
##root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph","JEC","JER","Trig","bTag",true)'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph","JEC","JER","Trig","bTag",true)'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph","JEC","JER","Trig","bTag",true)'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-700_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph","JEC","JER","Trig","bTag")'
root -l -b -q '../HbbHbb_Trigger.cc("$dir", "BulkGravTohhTohbbhbb_narrow_M-1400_13TeV-madgraph","JEC","JER","Trig","bTag")'
##root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-1600_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
##root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-2000_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'
 ##root -l -b -q '../HbbHbb_Trigger.cc("$dir", "GluGluToBulkGravitonToHHTo4B_M-3000_narrow_13TeV-madgraph","JEC","JER","Trig","bTag")'

